on:
  pull_request:
  push:
    branches:
      - master

name: Testing

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v3

      - name: install Dependencies
        run: |
          sudo apt-get -y install jq

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run unit tests
        run: cargo test
      # - name: "Install cargo-llvm-cov"
      #   uses: taiki-e/install-action@cargo-llvm-cov

      # - name: Generate line code coverage
      #   run: cargo llvm-cov test --ignore-filename-regex "src/single/tuple.rs" --html

      # - name: Upload html test artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: test-html
      #     path: target/llvm-cov/html/

      # - name: Generate summery code coverage
      #   run: cargo llvm-cov report --summary-only --ignore-filename-regex "src/single/tuple.rs" --json --output-path lcov.info

      # - name: Upload summery test artifact
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: test-summery
      #     path: lcov.info

      # - name: Try and Download old line coverage
      #   run: |
      #     curl -s https://api.github.com/repos/wasmcompute/tokactor/releases/latest
      #     | jq '.assets'

      # - name: Download master summery test artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: master-test-summery
      #     path: old-lcov.info

      # - name: Generate test summery report
      #   run: ./scripts/gen-summery.sh lcov.info old-lcov.info > summery.txt

      # - uses: actions/github-script@v6
      #   with:
      #     script: |
      #       const fs = require('fs')
      #       github.rest.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: fs.readFileSync('summery.txt', 'utf8')
      #       })
